spring.datasource.url=jdbc:postgresql://localhost:5432/viste_school
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=viste
spring.datasource.password=viste
spring.h2.console.enabled=false
